# ENVIRONMENT
#
# Running `npm start` assumes the default development environment. HTML and CSS
# are prettified for easy reading.
#
# Run `npm start prod` instead to render compact, minified HTML and CSS.

# CSS
# include: Places CSS styles in between `<style>` tags in the HTML output
#          file(s).
# file:    Saves CSS styles to a `styles.css` file in the `dist` directory.
# ref:     Same as 'file', but also places a CSS import tag at the top of the
#          HTML output file(s) to load the styles.
css: file
